[general]
default_syntax = "zsh"

[[syntax]]
name = "zsh"
block_start = "<%"
block_end = "%>"
comment_start = "<#"
comment_end = "#>"
expr_start = "<{"
expr_end = "}>"

[[escaper]]
path = "askama::filters::Text"
extensions = ["zsh"]
